/*
 *     Generated by class-dump 3.3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <AppKit/AppKit.h>
#import <InputMethodKit/InputMethodKit.h>

/*
 * File: /System/Library/Input Methods/PressAndHold.app/Contents/MacOS/PressAndHold
 * Arch: Intel x86-64 (x86_64)
 *
 *       Objective-C Garbage Collection: Unsupported
 */

@class PAHPanel, PAHWindowController, PAHCharacterRowView;

@interface PressAndHoldAppDelegate : NSObject <NSApplicationDelegate>
- (void)idleOut:(id)arg1;
- (void)resetIdleQuitTimer;
- (void)invalidateQuitTimer;

@property(readonly) PAHCharacterRowView *characterRow; // @dynamic characterRow;
@property(readonly) NSCharacterSet *acceptedCharacterSet; // @synthesize acceptedCharacterSet;
@property(readonly) IMKServer *server; // @synthesize server;
@property PAHWindowController *windowController; // @synthesize windowController;
@property PAHPanel *panel; // @synthesize panel;

@end

@interface PAHInputController : IMKInputController
- (NSString *)accentsStringForString:(NSString *)input language:(NSString *)languageCode;

- (BOOL)orderAccentsWindowFront:(id)arg1 client:(id)arg2;
- (void)orderAccentsWindowOut:(id)arg1;

- (BOOL)markSelectedAccentCharacter:(id)arg1;
- (BOOL)insertSelectedAccentCharacter:(id)arg1;
- (void)insertOriginalString:(id)arg1;

- (BOOL)isRelevantKeyCode:(unsigned short)arg1;
- (BOOL)didHandleControl:(id)arg1 client:(id)arg2;
- (BOOL)didHandleKeyDown:(id)arg1 client:(id)arg2;
- (void)selected:(id)arg1;
- (void)buildSelectionCharacterSetForString:(id)arg1;

- (CGRect)_characterRectForClient:(id)arg1;

@property(retain, nonatomic) NSCharacterSet *selectionCharSet; // @synthesize selectionCharSet;
@property(nonatomic) NSRange originalRange; // @synthesize originalRange;
@property(nonatomic) BOOL inSession; // @synthesize inSession;
@property(retain) NSString *originalString; // @synthesize originalString;
@property(retain, nonatomic) NSString *currentAccents; // @synthesize currentAccents;

@end

@interface PAHWindowController : NSWindowController
- (void)launchCharacterPanel:(id)arg1;
- (void)showAccentsWindow:(id)arg1 inputController:(id)arg2;

@property(retain) IMKInputController *inputController; // @synthesize inputController;

@end

@interface PAHPanel : NSPanel
@property(readonly) PAHCharacterRowView *characterRowView;

- (void)setAccents:(id)arg1 forCharacterRect:(CGRect)arg2 withCharacterRowTarget:(id)arg3 andAction:(SEL)arg4;

@end

@interface PAHContentView : NSView
- (double)horizontalCenterPositionOfFirstCell;
- (double)horizontalCenterPositionOfLastCell;
- (id)_outlinePathForRect:(CGRect)arg1;
- (id)_fillPathForRect:(CGRect)arg1;

@property BOOL arrowAtBottom; // @synthesize arrowAtBottom=_arrowAtBottom;
@property BOOL horizontalAlignmentOnLeft; // @synthesize horizontalAlignmentOnLeft=_horizontalAlignmentOnLeft;
@property(readonly) PAHCharacterRowView *characterRowView; // @synthesize characterRowView=_characterRowView;

@end

@interface PAHCharacterRowView : NSMatrix
@property(retain) NSString *string; // @dynamic string;

- (void)recalculateCharacterCells;
- (void)changeSelection:(BOOL)arg1;

- (void)selectFirstCellEqualToString:(id)arg1;
- (void)selectFirstCellNotEqualToString:(id)arg1;
- (void)highlightSelectCellAtRow:(NSUInteger)arg1 column:(NSUInteger)arg2 postSelectionBlock:(id)arg3;

- (CGPoint)centerOfFirstCell;
- (CGPoint)centerOfLastCell;

@end

@interface PAHTextCell : NSActionCell
- (void)setCandidate:(id)arg1 andIndexNumber:(NSUInteger)arg2;
@end

